# $HOME/.config/alacritty/alacritty.toml
# by Joshua Conter 2024-02-18

[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

[selection]

save_to_clipboard = true

# Colors (NightFox)

# Default colors
[colors.primary]
background = '#192330'
foreground = '#cdcecf'

# Normal colors
[colors.normal]
black   = '#393b44'
red     = '#c94f6d'
green   = '#81b29a'
yellow  = '#dbc074'
blue    = '#719cd6'
magenta = '#9d79d6'
cyan    = '#63cdcf'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#575860'
red     = '#d16983'
green   = '#8ebaa4'
yellow  = '#e0c989'
blue    = '#86abdc'
magenta = '#baa1e2'
cyan    = '#7ad5d6'
white   = '#e4e4e5'
